# Generated by Django 5.2 on 2025-05-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='freelance_status',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
