# Generated by Django 5.2 on 2025-05-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_profile_freelance_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('proficiency', models.PositiveIntegerField(help_text='Enter percentage between 0 and 100')),
            ],
        ),
    ]
